##################################################################
###################  Mob Defense configuration ###################
##################################################################

# Location of player spawn (x:y:z:yaw:pitch)
player-spawn-loc: 0.5:0.0:0.5:0.0:0.0

# Location of mob spawn (x:y:z:yaw:pitch)
spawn-loc: 0.5:0.0:0.5:0.0:0.0

# Location of mob objective (x:y:z:yaw:pitch)
end-loc: 0.5:0.0:0.5:0.0:0.0

# Location of towers seller (x:y:z:yaw:pitch)
npc-tower-loc: 0.5:0.0:0.5:0.0:0.0

# Location of tower upgrades seller (x:y:z:yaw:pitch)
npc-upgrades-loc: 0.5:0.0:0.5:0.0:0.0

# Location of exchanger (x:y:z:yaw:pitch)
npc-exchange-loc: 0.5:0.0:0.5:0.0:0.0

# The amount of gold nuggets you start with
start-money: 50

# The time (in seconds) between each wave, after the last mob of
# last wave spawned
wave-time: 42

# The number of mobs that can reach the end point before you loose
lives: 10
