name: MobDefense
main: fr.galaxyoyo.mobdefense.MobDefense
version: 1.2
author: galaxyoyo
after: NBTAPI

commands:
  mobdefense:
    permission: mobdefense.command
    aliases:
    - mobdef
    - mdef
    - mobd
    - md

permissions:
  mobdefense.command:
    default: op
